services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      args:
        BACKEND_PORT: ${BACKEND_PORT}
        CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./Backend:/app # Mount the local Backend directory to /app in the container
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}" # map the Host's FRONTEND_PORT to the container's FRONTEND_PORT port
    environment:
      - PORT=${FRONTEND_PORT} # Set the PORT environment variable to the FRONTEND_PORT value so that the React app listens on FRONTEND_PORT
    volumes:
      - ./Frontend:/app # Mount the local Frontend directory to /app in the container

networks:
  app-network:
    driver: bridge
